I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 58, in script
    $ player.location.call()
  File "game/script.rpy", line 58, in <module>
    $ player.location.call()
  File "game/core/locations/location.rpy", line 27, in call
    renpy.log(f"Calling Location with label: {self.label}")
AttributeError: 'Location' object has no attribute 'label'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 58, in script
    $ player.location.call()
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 58, in <module>
    $ player.location.call()
  File "game/core/locations/location.rpy", line 27, in call
    renpy.log(f"Calling Location with label: {self.label}")
AttributeError: 'Location' object has no attribute 'label'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
YoutubeVNGame 1.0
Wed Jul 10 18:18:02 2024
