I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1, in script
    init python:
  File "game/script.rpy", line 3, in <module>
    class Route(self, routeName):
NameError: name 'self' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1, in script
    init python:
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 3, in <module>
    class Route(self, routeName):
NameError: name 'self' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
VN GAME 1.0
Wed Jun  5 00:38:00 2024
